feat: add typestack component (resolves #16)
inclusive-design/idg-design-system pull request #19
Opened 2023-07-19 15:43 UTC by chosww

See #16 for details.

2023-07-19 17:56 UTC, greatislander requested changes
As discussed, we'll want to split these into components for:

Header Level 1
Header Level 2
Header Level 3
Header Level 3 (Card)
Header Level 4
Paragraph

2023-07-19 18:08 UTC, greatislander requested changes

2023-07-19 18:08 UTC, greatislander commented on src/_includes/layout.njk
> +    <link rel="stylesheet" href="/static/css/typestack.css" />
This is missing `font.css` which is why the fonts aren't appearing properly! Can you put it right after `variables.css`?

2023-07-19 18:52 UTC, greatislander requested changes
Can you remove the link styles from this? I would like to have a separate PR for that with the hover, focus and active states as well.

2023-07-19 19:41 UTC, chosww commented
Hey @greatislander I noticed that the classes used for height and width of color component is removed from your badge work, so the color page is broken. None of the space variables seems to give as big width and height as it was before, so should I create a custom class for bigger width and height using existing spacing variables? like calc(4*--space-something)

2023-07-20 00:50 UTC, greatislander commented on src/static/css/utilities.css
> +}
Are these used anymore?

2023-07-20 00:51 UTC, greatislander commented on src/_includes/components/typestack/typestack.config.js
> +    },
I think the default should be the paragraph. And let's call this component "Typography" rather than "Typestack".

2023-07-20 16:21 UTC, greatislander requested changes
Two final changes, @chosww — thanks!

2023-07-20 16:21 UTC, greatislander commented on src/_includes/components/typography/typography.config.js
> +        text: "Typography"
Let's make this the same as line 48 below.

2023-07-20 16:21 UTC, greatislander commented on src/static/css/utilities.css
> +}
This isn't used anywhere so we shouldn't add it yet.

2023-07-20 16:25 UTC, chosww commented
> Two final changes, @chosww — thanks!

Thanks for your review and feedback :)

2023-07-20 16:27 UTC, greatislander approved these changes

2023-07-20 16:27 UTC, merged