feat: pagination link component (resolves #10)
inclusive-design/idg-design-system pull request #29
Opened 2023-07-21 19:23 UTC by chosww

See #10 for details.

2023-07-21 19:42 UTC, greatislander requested changes
A couple changes to the gradient. Also, this still needs focus and active states!

2023-07-21 19:42 UTC, greatislander commented on src/static/css/_pagination.css
> +            269.79deg,
I think this should be 270deg.

2023-07-21 19:42 UTC, greatislander commented on src/static/css/_pagination.css
> +            ) -0.44%,
I think this should be 0%.

2023-07-21 19:42 UTC, greatislander commented on src/static/css/_pagination.css
> +            rgb(236 238 255 / 0%) 99.82%
It looks to me like this should be `var(--fl-bgColor, var(--color-white))`.

2023-07-21 19:42 UTC, greatislander commented on src/static/css/_pagination.css
> +    background: linear-gradient(90deg, var(--fl-bgColor, var(--pagination-bg)) 0%, rgb(236 238 255 / 0%) 100%);
Same as above, I think the `rgb` value should be `var(--fl-bgColor, var(--color-white))`.

2023-07-21 19:42 UTC, greatislander requested changes
A couple changes to the gradient. Also, this still needs focus and active states!

2023-07-21 19:52 UTC, chosww commented
> A couple changes to the gradient. Also, this still needs focus and active states!

Thanks for your review! I got the gradient values from Figma, so I assumed that would be correct. I forgot about the focus and active styles, I will add them now.

2023-07-24 11:40 UTC, greatislander commented
> > A couple changes to the gradient. Also, this still needs focus and active states!
> 
> Thanks for your review! I got the gradient values from Figma, so I assumed that would be correct. I forgot about the focus and active styles, I will add them now.

We were both right with respect to the colours— the gradients actually go to `color-blue-100`, not white. I converted the RGB to HSL and it matched. Can you make that change?

2023-07-24 11:45 UTC, greatislander commented
One issue with the focus state is that the focus ring as shown in the design should be inside the box and not outside.

You can see an example of how to address this using box-shadow on my draft PR for navigation:

https://github.com/inclusive-design/idg-design-system/blob/feat/navigation/src/static/css/_navigation.css#L19

https://github.com/inclusive-design/idg-design-system/blob/0479bcf5b398a8a2e31ae7d4f9a1967d934f8f15/src/static/css/_navigation.css#L89

Since you won't be using the `outline` for focus styles, you can set its colour to transparent.

2023-07-24 11:54 UTC, greatislander requested changes
One other note— even in the default state I think the top border and color should use `--fl-linkColor` to show that it's an interactive element.

2023-07-24 15:54 UTC, greatislander commented
> Thanks for your feedback! I set outline to "none" instead, since we don't use it, but if you think setting it to transparent is more appropriate, I will change it to transparent. Also, I added align-items center to the pagination class, because I noticed that the text in the button is not vertically centered.

The reason for the outline rule is described in the link below— and actually you should follow the syntax shown here (`outline: 3px solid transparent;`): https://sarahmhigley.com/writing/whcm-quick-tips/#1.-custom-focus-styles-%2B-a-transparent-outline

2023-07-24 15:59 UTC, chosww commented
> > Thanks for your feedback! I set outline to "none" instead, since we don't use it, but if you think setting it to transparent is more appropriate, I will change it to transparent. Also, I added align-items center to the pagination class, because I noticed that the text in the button is not vertically centered.
> 
> The reason for the outline rule is described in the link below— and actually you should follow the syntax shown here (`outline: 3px solid transparent;`): https://sarahmhigley.com/writing/whcm-quick-tips/#1.-custom-focus-styles-%2B-a-transparent-outline

Thanks for your explanation and the link!

2023-07-25 11:49 UTC, greatislander requested changes

2023-07-25 11:49 UTC, greatislander commented on src/static/css/_pagination.css
> +    box-shadow: 0 0 0 0.2rem var(--fl-linkColor, var(--pagination-box-shadow-color)) inset;
The width is 4px, or 0.25rem (4 / 16).

2023-07-25 11:49 UTC, greatislander commented on src/static/css/_pagination.css
> +    box-shadow: inset 0 0.2rem var(--fl-linkColor, var(--pagination-box-shadow-color));
The width is 4px, or 0.25rem (4 / 16).

2023-07-25 11:49 UTC, greatislander commented on src/_includes/components/pagination/pagination.njk
> +        <button class="pagination pagination-previous {{ params.variantClass }}">
These should be links, not buttons— can't believe I missed that before!

2023-07-25 11:49 UTC, greatislander commented on src/static/css/_pagination.css
> +    background: var(--fl-bgColor, var(--pagination-bg));
Add a third fallback to `color-blue-100` here so you don't need to define a variable globally for this:

```suggestion
    background: var(--fl-bgColor, var(--pagination-bg, var(--color-blue-100));
```

2023-07-25 11:49 UTC, greatislander commented on src/static/css/_pagination.css
> +    box-shadow: inset 0 0.2rem var(--fl-linkColor, var(--pagination-box-shadow-color));
Add a third fallback to `--color-blue-600` here so you don't need to define a variable globally for this:

```suggestion
    box-shadow: inset 0 0.2rem var(--fl-linkColor, var(--pagination-box-shadow-color, var(--color-blue-600)));
```

2023-07-25 11:49 UTC, greatislander commented on src/static/css/_pagination.css
> +    color: var(--fl-fgColor, var(--pagination-color));
Add a third fallback to `--color-blue-600` here so you don't need to define a variable globally for this:

```suggestion
    color: var(--fl-fgColor, var(--pagination-color, var(--color-blue-600)));
```

2023-07-25 11:49 UTC, greatislander commented on src/static/css/_variables.css
> +    --pagination-color: var(--color-blue-600);
These can be removed.

2023-07-25 14:23 UTC, greatislander requested changes
Final change: the pagination link should not be underlined, so you'll need to add a CSS rule to remove the underline.

2023-07-25 14:28 UTC, greatislander approved these changes

2023-07-25 14:28 UTC, merged